# Generated by Django 2.2.7 on 2019-11-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20191106_2214'),
        ('users', '0003_delete_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
